### ISSUE TITLE
TypeError: gulp.series is not a function

### ISSUE THREAD

**Issue by s-gaurav** [oracle/content-and-experience-toolkit#21]
**c:\CEC Toolkit\cec-src>cec et new-template**
Wed, 03 Aug 2022 14:24:55 GMT
Content Toolkit 22.7.2
[19:54:58] Working directory changed to C:\CEC Toolkit\content-and-experience-toolkit-master\sites\bin
[19:55:00] Using gulpfile C:\CEC Toolkit\content-and-experience-toolkit-master\sites\bin\gulpfile.js
[19:55:00] Starting 'export-template'...
 - template new-template
 - theme new-templateTheme
 - component IDCS-Login
 - component NavMenu
 - component StarterComponent
 - component StarterFooter
**C:\CEC Toolkit\content-and-experience-toolkit-master\sites\bin\template.js:2830
                                gulp.series('create-no-content-template-zip');
                                     ^

TypeError: gulp.series is not a function**
    at C:\CEC Toolkit\content-and-experience-toolkit-master\sites\bin\template.js:2830:10
    at new Promise (<anonymous>)
    at _exportTemplate (C:\CEC Toolkit\content-and-experience-toolkit-master\sites\bin\template.js:2598:9)
    at module.exports.exportTemplate (C:\CEC Toolkit\content-and-experience-toolkit-master\sites\bin\template.js:1255:2)
    at Gulp.<anonymous> (C:\CEC Toolkit\content-and-experience-toolkit-master\sites\bin\gulpfile.js:900:14)
    at module.exports (C:\CEC Toolkit\content-and-experience-toolkit-master\sites\node_modules\orchestrator\lib\runTask.js:34:7)
    at Orchestrator._runTask (C:\CEC Toolkit\content-and-experience-toolkit-master\sites\node_modules\orchestrator\index.js:273:3)
    at Orchestrator._runStep (C:\CEC Toolkit\content-and-experience-toolkit-master\sites\node_modules\orchestrator\index.js:214:10)
    at Orchestrator.start (C:\CEC Toolkit\content-and-experience-toolkit-master\sites\node_modules\orchestrator\index.js:134:8)
    at C:\CEC Toolkit\content-and-experience-toolkit-master\sites\node_modules\gulp\bin\gulp.js:129:20

Node.js v18.7.0
[19:55:03] Working directory changed to C:\CEC Toolkit\content-and-experience-toolkit-master\sites\bin
[19:55:05] Using gulpfile C:\CEC Toolkit\content-and-experience-toolkit-master\sites\bin\gulpfile.js
[19:55:05] Starting 'check-version'...
[19:55:05] Finished 'check-version' after 2.23 ms

Please suggest what is the error. I am able to create template but while exporting it gives error.

**Comment by hzeng99** [comment]
seems gulp version not right.
Could you check where is your gulp and its version?

where gulp
gulp -v

**Comment by s-gaurav** [comment]
﻿It’s 3.9.0 .
How to upgrade Gulp?

Thanks for quick response.

Gaurav

Sent from my iPhone

**Comment by hzeng99** [comment]
CLI installs the correct version but seems you have another install which is being used.
You could uninstall that one. 
Again, what the output of
  where gulp
