### ISSUE TITLE
2-step verification fail authenticate

### ISSUE THREAD

**Issue by JohnRSim** [oracle/content-and-experience-toolkit#3]
Unable to authenticate using toolkit when 2-step has been enabled from IDCS.

![Screenshot 2019-06-19 at 20 36 26](https://user-images.githubusercontent.com/364208/59749986-f887f780-9275-11e9-8a9e-ccca30603f30.png)

```bash
- copying smrtr-feed component
- optimizing component smrtr-feed
Optimization is not enabled for the component smrtr-feed
- created zip file /Applications/MAMP/htdocs/oracle/smrtr-oce/cec-components/dist/smrtr-feed.zip
ERROR: failed to connect to the server
{ TimeoutError: waiting for selector "pre" failed: timeout 30000ms exceeded
   at new WaitTask (/Applications/MAMP/htdocs/oracle/smrtr-oce/cec-components/node_modules/puppeteer/lib/DOMWorld.js:554:28)
   at DOMWorld._waitForSelectorOrXPath (/Applications/MAMP/htdocs/oracle/smrtr-oce/cec-components/node_modules/puppeteer/lib/DOMWorld.js:483:22)
   at DOMWorld.waitForSelector (/Applications/MAMP/htdocs/oracle/smrtr-oce/cec-components/node_modules/puppeteer/lib/DOMWorld.js:437:17)
   at Frame.waitForSelector (/Applications/MAMP/htdocs/oracle/smrtr-oce/cec-components/node_modules/puppeteer/lib/FrameManager.js:606:47)
   at Frame.<anonymous> (/Applications/MAMP/htdocs/oracle/smrtr-oce/cec-components/node_modules/puppeteer/lib/helper.js:109:23)
   at Page.waitForSelector (/Applications/MAMP/htdocs/oracle/smrtr-oce/cec-components/node_modules/puppeteer/lib/Page.js:1073:29)
   at loginServer (/Applications/MAMP/htdocs/oracle/smrtr-oce/cec-components/test/server/serverUtils.js:1880:16)
   at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }
- failed to connect to the server
```

**Comment by steveaburns** [comment]
@JohnRSim can you please verify if manually typing in the passcode from the email will get you past this screen.
Separately, we are working towards removing the need for puppeteer / headless chrome authentication for the CLI which will resolve the issue.

**Comment by steveaburns** [comment]
Added wait for up-to 2 minutes to allow entry of passcode.
We are moving off Idc Services to REST services, and puppeteer / headless chrome will not be needed.
